site_name: CASSINI

repo_url: https://github.com/cosmosz5/CompressedSensingImaging

nav:
    - Home: index.md
    - Compressed Sensing for SAM: about.md
    - Compressed Sensing PCA: cs_pca.md
    
theme:
    name: bootstrap4
    
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
